import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import { Activity, BarChart3, Barcode, Camera, Check, ChevronRight, Dumbbell, Flame, Heart, Home, Plus, Search, Settings, Trash2, Trophy, UserRound, Utensils, X, Droplets, Play, RotateCcw } from 'lucide-react'
import { foods, foodCount, Food } from './data/foods'

type Meal={id:number;food:Food;grams:number;mealType:string;createdAt:string}
type ScanItem={name:string;grams:number;kcal:number;protein:number;carbs:number;fat:number}
type Workout={id:number;name:string;duration:number;category:string;done:boolean}
const mealTypes=['Frühstück','Mittagessen','Abendessen','Snack']
const starterWorkouts:Workout[]=[
 {id:1,name:'Home Workout',duration:20,category:'Ganzkörper',done:false},
 {id:2,name:'Fußball Technik',duration:35,category:'Fußball',done:false},
 {id:3,name:'Core & Stabilität',duration:15,category:'Core',done:false},
 {id:4,name:'Locker Ausdauer',duration:30,category:'Ausdauer',done:false}
]
const calc=(f:Food,g:number)=>{const x=g/100;return{kcal:Math.round(f.kcal*x),protein:+(f.protein*x).toFixed(1),carbs:+(f.carbs*x).toFixed(1),fat:+(f.fat*x).toFixed(1)}}
const day=()=>new Date().toISOString().slice(0,10)

export default function App(){
 const [tab,setTab]=useState('home'),[q,setQ]=useState(''),[meals,setMeals]=useState<Meal[]>(()=>JSON.parse(localStorage.getItem('df-meals')||'[]')),
 [favs,setFavs]=useState<string[]>(()=>JSON.parse(localStorage.getItem('df-favs')||'[]')),[water,setWater]=useState(+localStorage.getItem('df-water')!||0),
 [workouts,setWorkouts]=useState<Workout[]>(()=>JSON.parse(localStorage.getItem('df-workouts')||JSON.stringify(starterWorkouts))),
 [food,setFood]=useState<Food|null>(null),[grams,setGrams]=useState(100),[mealType,setMealType]=useState('Frühstück'),
 [photo,setPhoto]=useState<string|null>(null),[scan,setScan]=useState<ScanItem[]>([]),[scanNote,setScanNote]=useState(''),[scanning,setScanning]=useState(false),[scanError,setScanError]=useState(''),
 [barcode,setBarcode]=useState(''),[product,setProduct]=useState<any>(null),[settings,setSettings]=useState(false),[workoutFilter,setWorkoutFilter]=useState('Alle'),[timer,setTimer]=useState<number|null>(null)
 useEffect(()=>localStorage.setItem('df-meals',JSON.stringify(meals)),[meals]);useEffect(()=>localStorage.setItem('df-favs',JSON.stringify(favs)),[favs]);useEffect(()=>localStorage.setItem('df-water',String(water)),[water]);useEffect(()=>localStorage.setItem('df-workouts',JSON.stringify(workouts)),[workouts])
 useEffect(()=>{if(timer===null)return;const t=setInterval(()=>setTimer(v=>v!==null&&v>0?v-1:0),1000);return()=>clearInterval(t)},[timer])
 const today=useMemo(()=>meals.filter(m=>m.createdAt===day()),[meals])
 const totals=useMemo(()=>today.reduce((a,m)=>{const c=calc(m.food,m.grams);return{...a,kcal:a.kcal+c.kcal,protein:a.protein+c.protein,carbs:a.carbs+c.carbs,fat:a.fat+c.fat}},{kcal:0,protein:0,carbs:0,fat:0}),[today])
 const filtered=useMemo(()=>foods.filter(f=>f.name.toLowerCase().includes(q.toLowerCase())||f.category.toLowerCase().includes(q.toLowerCase())).slice(0,80),[q])
 const done=workouts.filter(w=>w.done).length
 const week=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const k=d.toISOString().slice(0,10);return{label:d.toLocaleDateString('de-DE',{weekday:'short'}),kcal:meals.filter(m=>m.createdAt===k).reduce((s,m)=>s+calc(m.food,m.grams).kcal,0)}}),[meals])
 const addMeal=()=>{if(!food)return;setMeals(v=>[{id:Date.now(),food,grams,mealType,createdAt:day()},...v]);setFood(null)}
 const remove=(id:number)=>setMeals(v=>v.filter(m=>m.id!==id))
 const fileData=(f:File)=>new Promise<string>((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result));r.onerror=rej;r.readAsDataURL(f)})
 const scanPhoto=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setPhoto(URL.createObjectURL(f));setScanning(true);setScan([]);setScanError('');try{const image=await fileData(f);const r=await fetch('/api/analyze-food',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image})});const d=await r.json();if(!r.ok)throw Error(d.message||'Analyse fehlgeschlagen');setScan(d.items||[]);setScanNote(d.note||'')}catch(e:any){setScanError(e.message||'Foto konnte nicht analysiert werden.')}finally{setScanning(false)}}
 const saveScan=()=>{setMeals(v=>[...v,...scan.map((x,i)=>{const f=foods.find(a=>a.name.toLowerCase().includes(x.name.toLowerCase()))||{id:'scan'+Date.now()+i,name:x.name,category:'Foto-Scan',kcal:x.kcal*100/Math.max(1,x.grams),protein:x.protein*100/Math.max(1,x.grams),carbs:x.carbs*100/Math.max(1,x.grams),fat:x.fat*100/Math.max(1,x.grams)};return{id:Date.now()+i,food:f,grams:x.grams,mealType:'Mahlzeit',createdAt:day()}})]);setScan([]);setPhoto(null)}
 const lookup=async()=>{try{const r=await fetch('https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(barcode)+'?fields=product_name,brands,nutriments');const d=await r.json();if(d.status!==1)throw Error();const n=d.product.nutriments||{};setProduct({name:d.product.product_name||'Unbekanntes Produkt',brand:d.product.brands||'Marke unbekannt',kcal:Math.round(n['energy-kcal_100g']||0),protein:+(n.proteins_100g||0).toFixed(1),carbs:+(n.carbohydrates_100g||0).toFixed(1),fat:+(n.fat_100g||0).toFixed(1)})}catch{setProduct({error:'Produkt nicht gefunden'})}}
 const nav=[['home',Home,'Start'],['foods',Utensils,'Essen'],['training',Dumbbell,'Training'],['stats',BarChart3,'Stats'],['profile',UserRound,'Profil']] as const
 return <div className="app">
  <header className="top"><div className="brand"><div className="dragon">🐉</div><div><b>Dragon<span>Fuel</span></b><small>Eat · Move · Track</small></div></div><button className="round" onClick={()=>setSettings(true)}><Settings size={19}/></button></header>
  <main>
   {tab==='home'&&<section className="page">
    <div className="welcome"><div><small>HEUTE · {new Date().toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'2-digit'})}</small><h1>Dein Tag im <em>Überblick.</em></h1><p>Erfasse, was du isst und wie du dich bewegst.</p></div><div className="flame"><Flame/></div></div>
    <div className="summary"><div className="summaryMain"><small>ERFASSTE ENERGIE</small><b>{totals.kcal}</b><span>kcal heute</span></div><div className="summaryRing"><span>{today.length}</span><small>Mahlzeiten</small></div></div>
    <div className="quick"><button onClick={()=>document.getElementById('camera')?.click()}><Camera/><b>KI-Foto</b><small>Foto analysieren</small></button><button onClick={()=>setTab('foods')}><Utensils/><b>Essen</b><small>{foodCount}+ Lebensmittel</small></button><button onClick={()=>setTab('training')}><Dumbbell/><b>Training</b><small>{done} erledigt</small></button><button onClick={()=>setWater(w=>Math.min(5000,w+250))}><Droplets/><b>Wasser</b><small>{water} ml heute</small></button></div>
    <div className="sectionHead"><h2>Makros</h2><span>Richtwerte · keine Diätvorgabe</span></div>
    <div className="macros">{[['Protein',totals.protein,'g'],['Kohlenhydrate',totals.carbs,'g'],['Fett',totals.fat,'g']].map(([n,v,u])=><div className="macro" key={String(n)}><small>{n}</small><b>{v}{u}</b><div><i style={{width:Math.min(100,Number(v)*2)+'%'}}/></div></div>)}</div>
    <div className="sectionHead"><h2>Wasser</h2><span>{water} / 2000 ml</span></div><div className="water"><Droplets/><div className="waterbar"><i style={{width:Math.min(100,water/20)+'%'}}/></div><button onClick={()=>setWater(w=>Math.min(5000,w+250))}>+250 ml</button></div>
    <div className="sectionHead"><h2>Heute</h2><span>{today.length} Einträge</span></div>
    {!today.length?<div className="empty"><Utensils/><b>Noch nichts erfasst</b><span>Starte mit einem Foto oder wähle ein Lebensmittel.</span><button onClick={()=>setTab('foods')}>Essen hinzufügen <ChevronRight size={16}/></button></div>:<div className="list">{today.map(m=>{const c=calc(m.food,m.grams);return <div className="row" key={m.id}><div className="emoji">🍽️</div><div className="grow"><b>{m.food.name}</b><small>{m.mealType} · {m.grams} g</small></div><strong>{c.kcal} kcal</strong><button className="ghost" onClick={()=>remove(m.id)}><Trash2 size={16}/></button></div>})}</div>}
    <input id="camera" className="hidden" type="file" accept="image/*" capture="environment" onChange={scanPhoto}/>
    {(photo||scanning||scanError||scan.length>0)&&<div className="scan"><div className="sectionHead"><h2><Camera size={18}/> KI-Foto-Tracking</h2><button className="ghost" onClick={()=>{setPhoto(null);setScan([])}}><X size={17}/></button></div>{photo&&<img src={photo}/>} {scanning&&<div className="loading">Foto wird analysiert …</div>}{scanError&&<div className="error">{scanError}</div>}{scan.map((x,i)=><div className="scanrow" key={i}><div className="grow"><b>{x.name}</b><small>{x.kcal} kcal · P {x.protein} g</small></div><input value={x.grams} type="number" onChange={e=>setScan(v=>v.map((a,j)=>j===i?{...a,grams:+e.target.value}:a))}/><span>g</span></div>)}{scanNote&&<p>{scanNote}</p>}{scan.length>0&&<button className="primary" onClick={saveScan}><Check/> Speichern</button>}</div>}
   </section>}
   {tab==='foods'&&<section className="page"><div className="pageTitle"><div><small>FOOD DATABASE</small><h1>Lebensmittel</h1></div><b>{foodCount}+</b></div><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Suchen nach Lebensmittel …"/></div><div className="chips"><button onClick={()=>setQ('')}>Alle</button><button onClick={()=>setQ('Obst')}>Obst</button><button onClick={()=>setQ('Gemüse')}>Gemüse</button><button onClick={()=>setQ('Fleisch')}>Fleisch</button><button onClick={()=>setQ('Snack')}>Snacks</button></div><div className="list">{filtered.map(f=><button className="row food" key={f.id} onClick={()=>{setFood(f);setGrams(100)}}><div className="emoji">{f.category==='Obst'?'🍎':f.category==='Gemüse'?'🥦':f.category==='Fleisch'?'🍗':'🥗'}</div><div className="grow"><b>{f.name}</b><small>{f.category} · {f.kcal} kcal / 100 g</small></div><button className="heart" onClick={e=>{e.stopPropagation();setFavs(v=>v.includes(f.id)?v.filter(x=>x!==f.id):[...v,f.id])}}><Heart size={18} fill={favs.includes(f.id)?'currentColor':'none'}/></button><ChevronRight size={16}/></button>)}</div><div className="barcode"><Barcode/><div><b>Barcode-Scanner</b><small>Produkt über EAN suchen</small></div><div className="barcodeInput"><input value={barcode} onChange={e=>setBarcode(e.target.value)} placeholder="EAN"/><button onClick={lookup}>Suchen</button></div>{product&&<div className="product">{product.error?<b>{product.error}</b>:<><b>{product.name}</b><small>{product.brand}</small><span>{product.kcal} kcal · P {product.protein} · KH {product.carbs} · F {product.fat} / 100 g</span></>}</div>}</div></section>}
   {tab==='training'&&<section className="page"><div className="pageTitle"><div><small>MOVE</small><h1>Training</h1></div><div className="badge"><Flame size={15}/>{done}</div></div><div className="trainingIntro"><Trophy/><div><b>Bewegung, die dir Spaß macht</b><span>Wähle nach Lust und Zeit – nicht nach Druck.</span></div></div><div className="chips">{['Alle','Ganzkörper','Fußball','Core','Ausdauer'].map(x=><button className={workoutFilter===x?'active':''} onClick={()=>setWorkoutFilter(x)} key={x}>{x}</button>)}</div><div className="list">{workouts.filter(w=>workoutFilter==='Alle'||w.category===workoutFilter).map(w=><div className={'row workout '+(w.done?'completed':'')} key={w.id}><div className="workIcon"><Dumbbell/></div><div className="grow"><b>{w.name}</b><small>{w.category} · {w.duration} Min.</small></div><button className="timerBtn" onClick={()=>setTimer(w.duration*60)}><Play size={15}/></button><button className="check" onClick={()=>setWorkouts(v=>v.map(a=>a.id===w.id?{...a,done:!a.done}:a))}>{w.done?<Check/>:<Plus/>}</button></div>)}</div><div className="info"><Activity/><div><b>Heute zählt jede Bewegung.</b><span>DragonFuel bewertet dich nicht nach einer Zahl. Nutze Training für Fitness, Spaß und Fortschritt.</span></div></div></section>}
   {tab==='stats'&&<section className="page"><div className="pageTitle"><div><small>INSIGHTS</small><h1>Statistiken</h1></div><BarChart3/></div><div className="statGrid"><div><Flame/><b>{totals.kcal}</b><small>kcal erfasst</small></div><div><Utensils/><b>{today.length}</b><small>Mahlzeiten</small></div><div><Droplets/><b>{water}</b><small>ml Wasser</small></div><div><Heart/><b>{favs.length}</b><small>Favoriten</small></div></div><div className="chart"><div className="sectionHead"><h2>Letzte 7 Tage</h2><span>Erfassung</span></div><div className="bars">{week.map(x=><div key={x.label}><i style={{height:Math.max(8,Math.min(100,x.kcal/25))+'%'}}/><small>{x.label}</small></div>)}</div></div><div className="info"><BarChart3/><div><b>Deine Daten</b><span>Die App speichert deine Erfassung lokal auf diesem Gerät. Nährwerte und Fotoanalysen können Schätzungen sein.</span></div></div></section>}
   {tab==='profile'&&<section className="page"><div className="profile"><div className="avatar">🐉</div><div><small>DRAGONFUEL</small><h1>Dein Profil</h1><span>Kostenlose Basisversion</span></div></div><div className="settingsList"><button onClick={()=>setSettings(true)}><Settings/><div><b>Einstellungen</b><small>App, Daten & Datenschutz</small></div><ChevronRight/></button><button onClick={()=>setTab('foods')}><Heart/><div><b>Favoriten</b><small>{favs.length} gespeicherte Lebensmittel</small></div><ChevronRight/></button><button onClick={()=>setWater(0)}><Droplets/><div><b>Wasser zurücksetzen</b><small>Heutigen Zähler auf 0 setzen</small></div><ChevronRight/></button></div></section>}
  </main>
  <nav className="nav">{nav.map(([id,I,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I/><span>{label}</span></button>)}</nav>
  {timer!==null&&<div className="timer"><div><small>TRAINING TIMER</small><b>{String(Math.floor(timer/60)).padStart(2,'0')}:{String(timer%60).padStart(2,'0')}</b><span>Du kannst jederzeit pausieren oder stoppen.</span><div><button onClick={()=>setTimer(null)}><X/> Stoppen</button><button onClick={()=>setTimer(60)}><RotateCcw/> 1 Min</button></div></div></div>}
  {food&&<div className="modal"><div className="modalBox"><button className="close" onClick={()=>setFood(null)}><X/></button><small>{food.category}</small><h2>{food.name}</h2><span>{food.kcal} kcal / 100 g</span><label>Menge<input type="number" value={grams} min="1" onChange={e=>setGrams(Math.max(1,+e.target.value))}/><b>g</b></label><select value={mealType} onChange={e=>setMealType(e.target.value)}>{mealTypes.map(x=><option key={x}>{x}</option>)}</select><div className="nutrition">{Object.entries(calc(food,grams)).map(([k,v])=><span key={k}><small>{k}</small><b>{v}</b></span>)}</div><button className="primary" onClick={addMeal}><Plus/> Mahlzeit hinzufügen</button></div></div>}
  {settings&&<div className="modal"><div className="modalBox"><button className="close" onClick={()=>setSettings(false)}><X/></button><Settings/><h2>Einstellungen</h2><p>DragonFuel funktioniert auch ohne KI. Foto-Tracking liefert nur Schätzwerte und benötigt einen konfigurierten Vision-Dienst.</p><button className="danger" onClick={()=>{localStorage.clear();location.reload()}}>Alle lokalen Daten löschen</button></div></div>}
 </div>
}